[ES-6974] adding README to all example games
skillz/integration-examples pull request #10
Opened 2020-05-22 20:44 UTC by aaron-skillz

2020-05-22 20:45 UTC, jclin commented on 2048-Android/README.md
> +This project is integrated the Skillz SDK version 25.0.25. Check the [Downloads](https://developers.skillz.com/downloads) page for the latest version, and the instructions are located [here](https://
Typo, the version should be `25.0.22`

2020-05-22 20:45 UTC, jclin commented on 2048-iOS-Objc-C/README.md
> +This project is integrated the Skillz SDK version 25.0.25. Check the [Downloads](https://developers.skillz.com/downloads) page for the latest version, and the instructions are located [here](https://
Same thing here

2020-05-22 20:46 UTC, jclin commented on 2048-iOS-Swift/README.md
> +This project is integrated the Skillz SDK version 25.0.25. Check the [Downloads](https://developers.skillz.com/downloads) page for the latest version, and the instructions are located [here](https://
And here.

2020-05-22 20:48 UTC, jclin commented
Just need to use `25.0.22` as the SDK version in all the READMEs.

2020-05-22 20:49 UTC, jclin requested changes
Just need to update all the READMEs to use `25.0.22` as the SDK version.

2020-05-23 01:08 UTC, trig-skillz commented
👍

2020-05-23 01:10 UTC, jclin approved these changes
:shipit:

2020-05-23 01:11 UTC, merged